### ISSUE TITLE
Making it work only in Release

### ISSUE THREAD

**Issue by igorkulman** [antiufo/roslyn-linq-rewrite#13]
Is there a way to make it work only in release? So there is no "slowdown" when starting the project do debug it.

**Comment by antiufo** [comment]
I suppose you're specifically talking about project.json, as opposed to csproj, in which you just use a different command line, correct?

**Comment by igorkulman** [comment]
Yes, talking about using it with project.json in a Windows Phone project. What do you mean by different command line?

**Comment by antiufo** [comment]
I'm taking about the fact that in order to use the tool with sln/csproj, you directly call roslyn-linq-rewrite app.csproj, as opposed to msbuild

**Comment by antiufo** [comment]
Yes it probably makes sense to only optimize linq when ordinary c# optimizations are on. The only minor problem with this is that dotnet build always recompiles dependencies that use custom compilers, but that's another issue
