### ISSUE TITLE
Provide the rewrite engine as a Nuget Package

### ISSUE THREAD

**Issue by redknightlois** [antiufo/roslyn-linq-rewrite#17]
Is there any intention to support the scenario of optimization of runtime generated code?

**Comment by antiufo** [comment]
No nuget packages are currently provided, but you could easily add a reference to roslynlinqrewrite.csproj. The code also includes some examples of small code snippets being processed (without depending on msbuild or csc).  You can then use the ordinary roslyn emit methods to create an on-disk or in-memory assembly.
