### ISSUE TITLE
Typo in the output code

### ISSUE THREAD

**Issue by mdpopescu** [antiufo/roslyn-linq-rewrite#2]
Hi, you probably made some manual changes in the output code because there's a typo in there; this line

`num += num2 + 3;`

should be

`num += _linqitems[i] + 3;`

**Comment by mattwarren** [comment]
I've just noticed this issue, if it helps I've sent a PR that fixes this, see https://github.com/antiufo/roslyn-linq-rewrite/pull/4

**Comment by antiufo** [comment]
Thank you @mattwarren, although I just pushed an updated version.
